<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SmsEnvios extends \AppBundle\Entity\SmsEnvios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'idsms', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'idcampania', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'fechaingreso', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'mensaje', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'fechaenviado', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'enviado', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'idsender', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'idsmsdbtempBorrar', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'coltempBorrar');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'idsms', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'idcampania', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'fechaingreso', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'mensaje', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'fechaenviado', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'enviado', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'idsender', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'idsmsdbtempBorrar', '' . "\0" . 'AppBundle\\Entity\\SmsEnvios' . "\0" . 'coltempBorrar');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SmsEnvios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdsms()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdsms();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsms', array());

        return parent::getIdsms();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcampania($idcampania)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcampania', array($idcampania));

        return parent::setIdcampania($idcampania);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcampania()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcampania', array());

        return parent::getIdcampania();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaingreso($fechaingreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaingreso', array($fechaingreso));

        return parent::setFechaingreso($fechaingreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaingreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaingreso', array());

        return parent::getFechaingreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setMensaje($mensaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMensaje', array($mensaje));

        return parent::setMensaje($mensaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getMensaje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMensaje', array());

        return parent::getMensaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaenviado($fechaenviado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaenviado', array($fechaenviado));

        return parent::setFechaenviado($fechaenviado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaenviado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaenviado', array());

        return parent::getFechaenviado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnviado($enviado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnviado', array($enviado));

        return parent::setEnviado($enviado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnviado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnviado', array());

        return parent::getEnviado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsender($idsender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsender', array($idsender));

        return parent::setIdsender($idsender);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsender', array());

        return parent::getIdsender();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', array($observaciones));

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', array());

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsmsdbtempBorrar($idsmsdbtempBorrar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsmsdbtempBorrar', array($idsmsdbtempBorrar));

        return parent::setIdsmsdbtempBorrar($idsmsdbtempBorrar);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsmsdbtempBorrar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsmsdbtempBorrar', array());

        return parent::getIdsmsdbtempBorrar();
    }

    /**
     * {@inheritDoc}
     */
    public function setColtempBorrar($coltempBorrar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColtempBorrar', array($coltempBorrar));

        return parent::setColtempBorrar($coltempBorrar);
    }

    /**
     * {@inheritDoc}
     */
    public function getColtempBorrar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColtempBorrar', array());

        return parent::getColtempBorrar();
    }

}
