<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cobrosparciales extends \AppBundle\Entity\Cobrosparciales implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'idcobrop', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'idfactura', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'importe', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'fechaingreso', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'fechapago', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'idmediopago', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'terminalId', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'termSeqNum', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'fechainformadoOl', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'anulado', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'idpago', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'identidad');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'idcobrop', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'idfactura', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'importe', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'fechaingreso', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'fechapago', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'idmediopago', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'terminalId', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'termSeqNum', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'fechainformadoOl', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'anulado', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'idpago', '' . "\0" . 'AppBundle\\Entity\\Cobrosparciales' . "\0" . 'identidad');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cobrosparciales $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdcobrop()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdcobrop();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcobrop', array());

        return parent::getIdcobrop();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdfactura($idfactura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdfactura', array($idfactura));

        return parent::setIdfactura($idfactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdfactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfactura', array());

        return parent::getIdfactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setImporte($importe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporte', array($importe));

        return parent::setImporte($importe);
    }

    /**
     * {@inheritDoc}
     */
    public function getImporte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporte', array());

        return parent::getImporte();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaingreso($fechaingreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaingreso', array($fechaingreso));

        return parent::setFechaingreso($fechaingreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaingreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaingreso', array());

        return parent::getFechaingreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechapago($fechapago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechapago', array($fechapago));

        return parent::setFechapago($fechapago);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechapago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechapago', array());

        return parent::getFechapago();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmediopago($idmediopago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmediopago', array($idmediopago));

        return parent::setIdmediopago($idmediopago);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmediopago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmediopago', array());

        return parent::getIdmediopago();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', array($observaciones));

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', array());

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerminalId($terminalId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerminalId', array($terminalId));

        return parent::setTerminalId($terminalId);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerminalId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerminalId', array());

        return parent::getTerminalId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTermSeqNum($termSeqNum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTermSeqNum', array($termSeqNum));

        return parent::setTermSeqNum($termSeqNum);
    }

    /**
     * {@inheritDoc}
     */
    public function getTermSeqNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTermSeqNum', array());

        return parent::getTermSeqNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechainformadoOl($fechainformadoOl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechainformadoOl', array($fechainformadoOl));

        return parent::setFechainformadoOl($fechainformadoOl);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechainformadoOl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechainformadoOl', array());

        return parent::getFechainformadoOl();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnulado($anulado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnulado', array($anulado));

        return parent::setAnulado($anulado);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnulado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnulado', array());

        return parent::getAnulado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpago($idpago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpago', array($idpago));

        return parent::setIdpago($idpago);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpago', array());

        return parent::getIdpago();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentidad($identidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentidad', array($identidad));

        return parent::setIdentidad($identidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentidad', array());

        return parent::getIdentidad();
    }

}
