<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Facturas extends \AppBundle\Entity\Facturas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'idfactura', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'idusuario', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'idservicio', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'fechaemision', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'fechavto', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'fechavto2', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'tipofactura', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'nrofactura', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'descuento', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'importeBruto', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'importeBruto2', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'iva', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'observacion', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'fechaingreso', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'idaccion', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'tipo', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'fechaestado', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'moneda', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'cae', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'nombrearchivo', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'comentarios', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'idtipodocumento', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'importeBrutoVencido', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'idmoneda', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'url', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'migrated');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'idfactura', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'idusuario', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'idservicio', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'fechaemision', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'fechavto', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'fechavto2', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'tipofactura', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'nrofactura', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'descuento', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'importeBruto', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'importeBruto2', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'iva', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'observacion', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'fechaingreso', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'idaccion', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'tipo', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'fechaestado', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'moneda', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'cae', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'nombrearchivo', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'comentarios', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'idtipodocumento', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'importeBrutoVencido', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'idmoneda', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'url', '' . "\0" . 'AppBundle\\Entity\\Facturas' . "\0" . 'migrated');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Facturas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdfactura()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getIdfactura();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfactura', array());

        return parent::getIdfactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuario($idusuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuario', array($idusuario));

        return parent::setIdusuario($idusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', array());

        return parent::getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdservicio($idservicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdservicio', array($idservicio));

        return parent::setIdservicio($idservicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdservicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdservicio', array());

        return parent::getIdservicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaemision($fechaemision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaemision', array($fechaemision));

        return parent::setFechaemision($fechaemision);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaemision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaemision', array());

        return parent::getFechaemision();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechavto($fechavto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechavto', array($fechavto));

        return parent::setFechavto($fechavto);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechavto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechavto', array());

        return parent::getFechavto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechavto2($fechavto2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechavto2', array($fechavto2));

        return parent::setFechavto2($fechavto2);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechavto2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechavto2', array());

        return parent::getFechavto2();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipofactura($tipofactura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipofactura', array($tipofactura));

        return parent::setTipofactura($tipofactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipofactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipofactura', array());

        return parent::getTipofactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setNrofactura($nrofactura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNrofactura', array($nrofactura));

        return parent::setNrofactura($nrofactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getNrofactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNrofactura', array());

        return parent::getNrofactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescuento($descuento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescuento', array($descuento));

        return parent::setDescuento($descuento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescuento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescuento', array());

        return parent::getDescuento();
    }

    /**
     * {@inheritDoc}
     */
    public function setImporteBruto($importeBruto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporteBruto', array($importeBruto));

        return parent::setImporteBruto($importeBruto);
    }

    /**
     * {@inheritDoc}
     */
    public function getImporteBruto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporteBruto', array());

        return parent::getImporteBruto();
    }

    /**
     * {@inheritDoc}
     */
    public function setImporteBruto2($importeBruto2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporteBruto2', array($importeBruto2));

        return parent::setImporteBruto2($importeBruto2);
    }

    /**
     * {@inheritDoc}
     */
    public function getImporteBruto2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporteBruto2', array());

        return parent::getImporteBruto2();
    }

    /**
     * {@inheritDoc}
     */
    public function setIva($iva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIva', array($iva));

        return parent::setIva($iva);
    }

    /**
     * {@inheritDoc}
     */
    public function getIva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIva', array());

        return parent::getIva();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', array($observacion));

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', array());

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaingreso($fechaingreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaingreso', array($fechaingreso));

        return parent::setFechaingreso($fechaingreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaingreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaingreso', array());

        return parent::getFechaingreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdaccion($idaccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdaccion', array($idaccion));

        return parent::setIdaccion($idaccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdaccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdaccion', array());

        return parent::getIdaccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaestado($fechaestado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaestado', array($fechaestado));

        return parent::setFechaestado($fechaestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaestado', array());

        return parent::getFechaestado();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneda($moneda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneda', array($moneda));

        return parent::setMoneda($moneda);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneda', array());

        return parent::getMoneda();
    }

    /**
     * {@inheritDoc}
     */
    public function setCae($cae)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCae', array($cae));

        return parent::setCae($cae);
    }

    /**
     * {@inheritDoc}
     */
    public function getCae()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCae', array());

        return parent::getCae();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombrearchivo($nombrearchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombrearchivo', array($nombrearchivo));

        return parent::setNombrearchivo($nombrearchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombrearchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombrearchivo', array());

        return parent::getNombrearchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setComentarios($comentarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComentarios', array($comentarios));

        return parent::setComentarios($comentarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getComentarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentarios', array());

        return parent::getComentarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtipodocumento($idtipodocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtipodocumento', array($idtipodocumento));

        return parent::setIdtipodocumento($idtipodocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtipodocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipodocumento', array());

        return parent::getIdtipodocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setImporteBrutoVencido($importeBrutoVencido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporteBrutoVencido', array($importeBrutoVencido));

        return parent::setImporteBrutoVencido($importeBrutoVencido);
    }

    /**
     * {@inheritDoc}
     */
    public function getImporteBrutoVencido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporteBrutoVencido', array());

        return parent::getImporteBrutoVencido();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmoneda($idmoneda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmoneda', array($idmoneda));

        return parent::setIdmoneda($idmoneda);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmoneda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmoneda', array());

        return parent::getIdmoneda();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setMigrated($migrated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMigrated', array($migrated));

        return parent::setMigrated($migrated);
    }

    /**
     * {@inheritDoc}
     */
    public function getMigrated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMigrated', array());

        return parent::getMigrated();
    }

}
