<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Notasdebito extends \AppBundle\Entity\Notasdebito implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'idnotadebito', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'idservicio', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'tiponota', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'notadebito', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'fechaemision', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'fechavto', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'fechaingreso', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'importe', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'idfactura', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'estado');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'idnotadebito', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'idservicio', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'tiponota', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'notadebito', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'fechaemision', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'fechavto', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'fechaingreso', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'importe', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'idfactura', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Notasdebito' . "\0" . 'estado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Notasdebito $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdnotadebito()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdnotadebito();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdnotadebito', array());

        return parent::getIdnotadebito();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdservicio($idservicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdservicio', array($idservicio));

        return parent::setIdservicio($idservicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdservicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdservicio', array());

        return parent::getIdservicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setTiponota($tiponota)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTiponota', array($tiponota));

        return parent::setTiponota($tiponota);
    }

    /**
     * {@inheritDoc}
     */
    public function getTiponota()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTiponota', array());

        return parent::getTiponota();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotadebito($notadebito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotadebito', array($notadebito));

        return parent::setNotadebito($notadebito);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotadebito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotadebito', array());

        return parent::getNotadebito();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaemision($fechaemision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaemision', array($fechaemision));

        return parent::setFechaemision($fechaemision);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaemision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaemision', array());

        return parent::getFechaemision();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechavto($fechavto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechavto', array($fechavto));

        return parent::setFechavto($fechavto);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechavto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechavto', array());

        return parent::getFechavto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaingreso($fechaingreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaingreso', array($fechaingreso));

        return parent::setFechaingreso($fechaingreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaingreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaingreso', array());

        return parent::getFechaingreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setImporte($importe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporte', array($importe));

        return parent::setImporte($importe);
    }

    /**
     * {@inheritDoc}
     */
    public function getImporte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporte', array());

        return parent::getImporte();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdfactura($idfactura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdfactura', array($idfactura));

        return parent::setIdfactura($idfactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdfactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfactura', array());

        return parent::getIdfactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', array($observaciones));

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', array());

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

}
