<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PagofacilCredenciales extends \AppBundle\Entity\PagofacilCredenciales implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'idcredencial', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'idservicio', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'codcredencialpf', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'idcliente', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'prefijo', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'nro', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'fechageneracion', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'codcredencialpfRecortado', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'idarchivo', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'credonline');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'idcredencial', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'idservicio', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'codcredencialpf', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'idcliente', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'prefijo', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'nro', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'fechageneracion', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'codcredencialpfRecortado', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'idarchivo', '' . "\0" . 'AppBundle\\Entity\\PagofacilCredenciales' . "\0" . 'credonline');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PagofacilCredenciales $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdcredencial()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdcredencial();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcredencial', array());

        return parent::getIdcredencial();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdservicio($idservicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdservicio', array($idservicio));

        return parent::setIdservicio($idservicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdservicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdservicio', array());

        return parent::getIdservicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodcredencialpf($codcredencialpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodcredencialpf', array($codcredencialpf));

        return parent::setCodcredencialpf($codcredencialpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodcredencialpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodcredencialpf', array());

        return parent::getCodcredencialpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcliente($idcliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcliente', array($idcliente));

        return parent::setIdcliente($idcliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcliente', array());

        return parent::getIdcliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrefijo($prefijo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrefijo', array($prefijo));

        return parent::setPrefijo($prefijo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrefijo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrefijo', array());

        return parent::getPrefijo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNro($nro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNro', array($nro));

        return parent::setNro($nro);
    }

    /**
     * {@inheritDoc}
     */
    public function getNro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNro', array());

        return parent::getNro();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechageneracion($fechageneracion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechageneracion', array($fechageneracion));

        return parent::setFechageneracion($fechageneracion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechageneracion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechageneracion', array());

        return parent::getFechageneracion();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodcredencialpfRecortado($codcredencialpfRecortado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodcredencialpfRecortado', array($codcredencialpfRecortado));

        return parent::setCodcredencialpfRecortado($codcredencialpfRecortado);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodcredencialpfRecortado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodcredencialpfRecortado', array());

        return parent::getCodcredencialpfRecortado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdarchivo($idarchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdarchivo', array($idarchivo));

        return parent::setIdarchivo($idarchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdarchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdarchivo', array());

        return parent::getIdarchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCredonline($credonline)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredonline', array($credonline));

        return parent::setCredonline($credonline);
    }

    /**
     * {@inheritDoc}
     */
    public function getCredonline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredonline', array());

        return parent::getCredonline();
    }

}
