<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TablatempTama2 extends \AppBundle\Entity\TablatempTama2 implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col1', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col2', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col3', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col4', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col5', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col6', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col7', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col8', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col9', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col10');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col1', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col2', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col3', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col4', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col5', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col6', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col7', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col8', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col9', '' . "\0" . 'AppBundle\\Entity\\TablatempTama2' . "\0" . 'col10');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TablatempTama2 $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCol1($col1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCol1', array($col1));

        return parent::setCol1($col1);
    }

    /**
     * {@inheritDoc}
     */
    public function getCol1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCol1', array());

        return parent::getCol1();
    }

    /**
     * {@inheritDoc}
     */
    public function setCol2($col2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCol2', array($col2));

        return parent::setCol2($col2);
    }

    /**
     * {@inheritDoc}
     */
    public function getCol2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCol2', array());

        return parent::getCol2();
    }

    /**
     * {@inheritDoc}
     */
    public function setCol3($col3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCol3', array($col3));

        return parent::setCol3($col3);
    }

    /**
     * {@inheritDoc}
     */
    public function getCol3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCol3', array());

        return parent::getCol3();
    }

    /**
     * {@inheritDoc}
     */
    public function setCol4($col4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCol4', array($col4));

        return parent::setCol4($col4);
    }

    /**
     * {@inheritDoc}
     */
    public function getCol4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCol4', array());

        return parent::getCol4();
    }

    /**
     * {@inheritDoc}
     */
    public function setCol5($col5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCol5', array($col5));

        return parent::setCol5($col5);
    }

    /**
     * {@inheritDoc}
     */
    public function getCol5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCol5', array());

        return parent::getCol5();
    }

    /**
     * {@inheritDoc}
     */
    public function setCol6($col6)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCol6', array($col6));

        return parent::setCol6($col6);
    }

    /**
     * {@inheritDoc}
     */
    public function getCol6()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCol6', array());

        return parent::getCol6();
    }

    /**
     * {@inheritDoc}
     */
    public function setCol7($col7)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCol7', array($col7));

        return parent::setCol7($col7);
    }

    /**
     * {@inheritDoc}
     */
    public function getCol7()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCol7', array());

        return parent::getCol7();
    }

    /**
     * {@inheritDoc}
     */
    public function setCol8($col8)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCol8', array($col8));

        return parent::setCol8($col8);
    }

    /**
     * {@inheritDoc}
     */
    public function getCol8()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCol8', array());

        return parent::getCol8();
    }

    /**
     * {@inheritDoc}
     */
    public function setCol9($col9)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCol9', array($col9));

        return parent::setCol9($col9);
    }

    /**
     * {@inheritDoc}
     */
    public function getCol9()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCol9', array());

        return parent::getCol9();
    }

    /**
     * {@inheritDoc}
     */
    public function setCol10($col10)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCol10', array($col10));

        return parent::setCol10($col10);
    }

    /**
     * {@inheritDoc}
     */
    public function getCol10()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCol10', array());

        return parent::getCol10();
    }

}
