<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ExamenesRespuestas extends \AppBundle\Entity\ExamenesRespuestas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\ExamenesRespuestas' . "\0" . 'idrespuesta', '' . "\0" . 'AppBundle\\Entity\\ExamenesRespuestas' . "\0" . 'idpregunta', '' . "\0" . 'AppBundle\\Entity\\ExamenesRespuestas' . "\0" . 'detalle', '' . "\0" . 'AppBundle\\Entity\\ExamenesRespuestas' . "\0" . 'correcto', '' . "\0" . 'AppBundle\\Entity\\ExamenesRespuestas' . "\0" . 'estado');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\ExamenesRespuestas' . "\0" . 'idrespuesta', '' . "\0" . 'AppBundle\\Entity\\ExamenesRespuestas' . "\0" . 'idpregunta', '' . "\0" . 'AppBundle\\Entity\\ExamenesRespuestas' . "\0" . 'detalle', '' . "\0" . 'AppBundle\\Entity\\ExamenesRespuestas' . "\0" . 'correcto', '' . "\0" . 'AppBundle\\Entity\\ExamenesRespuestas' . "\0" . 'estado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ExamenesRespuestas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdrespuesta()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdrespuesta();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdrespuesta', array());

        return parent::getIdrespuesta();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpregunta($idpregunta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpregunta', array($idpregunta));

        return parent::setIdpregunta($idpregunta);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpregunta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpregunta', array());

        return parent::getIdpregunta();
    }

    /**
     * {@inheritDoc}
     */
    public function setDetalle($detalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetalle', array($detalle));

        return parent::setDetalle($detalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalle', array());

        return parent::getDetalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorrecto($correcto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorrecto', array($correcto));

        return parent::setCorrecto($correcto);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorrecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorrecto', array());

        return parent::getCorrecto();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

}
