<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SisFacturasTest extends \AppBundle\Entity\SisFacturasTest implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'idfactura', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'idcliente', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'tipofactura', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'puntodeventa', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'nrofactura', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'fechaalta', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'mesdatos', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'aniodatos', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'fechaemision', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'fechavto', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'importeBruto', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'iva', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'cae', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'idtipoFactura', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'motivo', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'idsolicitud', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'resultado', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'fechamail', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'idempresa', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'importeTotal');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'idfactura', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'idcliente', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'tipofactura', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'puntodeventa', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'nrofactura', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'fechaalta', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'mesdatos', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'aniodatos', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'fechaemision', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'fechavto', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'importeBruto', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'iva', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'cae', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'idtipoFactura', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'motivo', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'idsolicitud', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'resultado', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'fechamail', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'idempresa', '' . "\0" . 'AppBundle\\Entity\\SisFacturasTest' . "\0" . 'importeTotal');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SisFacturasTest $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdfactura()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdfactura();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfactura', array());

        return parent::getIdfactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcliente($idcliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcliente', array($idcliente));

        return parent::setIdcliente($idcliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcliente', array());

        return parent::getIdcliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipofactura($tipofactura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipofactura', array($tipofactura));

        return parent::setTipofactura($tipofactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipofactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipofactura', array());

        return parent::getTipofactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setPuntodeventa($puntodeventa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuntodeventa', array($puntodeventa));

        return parent::setPuntodeventa($puntodeventa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuntodeventa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuntodeventa', array());

        return parent::getPuntodeventa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNrofactura($nrofactura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNrofactura', array($nrofactura));

        return parent::setNrofactura($nrofactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getNrofactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNrofactura', array());

        return parent::getNrofactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaalta($fechaalta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaalta', array($fechaalta));

        return parent::setFechaalta($fechaalta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaalta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaalta', array());

        return parent::getFechaalta();
    }

    /**
     * {@inheritDoc}
     */
    public function setMesdatos($mesdatos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMesdatos', array($mesdatos));

        return parent::setMesdatos($mesdatos);
    }

    /**
     * {@inheritDoc}
     */
    public function getMesdatos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMesdatos', array());

        return parent::getMesdatos();
    }

    /**
     * {@inheritDoc}
     */
    public function setAniodatos($aniodatos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAniodatos', array($aniodatos));

        return parent::setAniodatos($aniodatos);
    }

    /**
     * {@inheritDoc}
     */
    public function getAniodatos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAniodatos', array());

        return parent::getAniodatos();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaemision($fechaemision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaemision', array($fechaemision));

        return parent::setFechaemision($fechaemision);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaemision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaemision', array());

        return parent::getFechaemision();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechavto($fechavto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechavto', array($fechavto));

        return parent::setFechavto($fechavto);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechavto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechavto', array());

        return parent::getFechavto();
    }

    /**
     * {@inheritDoc}
     */
    public function setImporteBruto($importeBruto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporteBruto', array($importeBruto));

        return parent::setImporteBruto($importeBruto);
    }

    /**
     * {@inheritDoc}
     */
    public function getImporteBruto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporteBruto', array());

        return parent::getImporteBruto();
    }

    /**
     * {@inheritDoc}
     */
    public function setIva($iva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIva', array($iva));

        return parent::setIva($iva);
    }

    /**
     * {@inheritDoc}
     */
    public function getIva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIva', array());

        return parent::getIva();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCae($cae)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCae', array($cae));

        return parent::setCae($cae);
    }

    /**
     * {@inheritDoc}
     */
    public function getCae()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCae', array());

        return parent::getCae();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtipoFactura($idtipoFactura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtipoFactura', array($idtipoFactura));

        return parent::setIdtipoFactura($idtipoFactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtipoFactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipoFactura', array());

        return parent::getIdtipoFactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivo($motivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivo', array($motivo));

        return parent::setMotivo($motivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivo', array());

        return parent::getMotivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsolicitud($idsolicitud)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsolicitud', array($idsolicitud));

        return parent::setIdsolicitud($idsolicitud);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsolicitud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsolicitud', array());

        return parent::getIdsolicitud();
    }

    /**
     * {@inheritDoc}
     */
    public function setResultado($resultado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResultado', array($resultado));

        return parent::setResultado($resultado);
    }

    /**
     * {@inheritDoc}
     */
    public function getResultado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResultado', array());

        return parent::getResultado();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechamail($fechamail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechamail', array($fechamail));

        return parent::setFechamail($fechamail);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechamail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechamail', array());

        return parent::getFechamail();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdempresa($idempresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdempresa', array($idempresa));

        return parent::setIdempresa($idempresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdempresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdempresa', array());

        return parent::getIdempresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setImporteTotal($importeTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporteTotal', array($importeTotal));

        return parent::setImporteTotal($importeTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getImporteTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporteTotal', array());

        return parent::getImporteTotal();
    }

}
