<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Debitos extends \AppBundle\Entity\Debitos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'iddebito', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'idfactura', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'fechaEnvio', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'fechaProcesoRgp', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'fechaDebito', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'banco', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'cbu', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'fechaIngresoResultado', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'informado', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'idcliente', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'idestado');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'iddebito', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'idfactura', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'fechaEnvio', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'fechaProcesoRgp', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'fechaDebito', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'banco', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'cbu', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'fechaIngresoResultado', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'informado', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'idcliente', '' . "\0" . 'AppBundle\\Entity\\Debitos' . "\0" . 'idestado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Debitos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIddebito()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIddebito();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIddebito', array());

        return parent::getIddebito();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdfactura($idfactura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdfactura', array($idfactura));

        return parent::setIdfactura($idfactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdfactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfactura', array());

        return parent::getIdfactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaEnvio($fechaEnvio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEnvio', array($fechaEnvio));

        return parent::setFechaEnvio($fechaEnvio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEnvio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEnvio', array());

        return parent::getFechaEnvio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaProcesoRgp($fechaProcesoRgp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaProcesoRgp', array($fechaProcesoRgp));

        return parent::setFechaProcesoRgp($fechaProcesoRgp);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaProcesoRgp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaProcesoRgp', array());

        return parent::getFechaProcesoRgp();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaDebito($fechaDebito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaDebito', array($fechaDebito));

        return parent::setFechaDebito($fechaDebito);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaDebito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaDebito', array());

        return parent::getFechaDebito();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setBanco($banco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBanco', array($banco));

        return parent::setBanco($banco);
    }

    /**
     * {@inheritDoc}
     */
    public function getBanco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBanco', array());

        return parent::getBanco();
    }

    /**
     * {@inheritDoc}
     */
    public function setCbu($cbu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCbu', array($cbu));

        return parent::setCbu($cbu);
    }

    /**
     * {@inheritDoc}
     */
    public function getCbu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCbu', array());

        return parent::getCbu();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaIngresoResultado($fechaIngresoResultado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaIngresoResultado', array($fechaIngresoResultado));

        return parent::setFechaIngresoResultado($fechaIngresoResultado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaIngresoResultado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaIngresoResultado', array());

        return parent::getFechaIngresoResultado();
    }

    /**
     * {@inheritDoc}
     */
    public function setInformado($informado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInformado', array($informado));

        return parent::setInformado($informado);
    }

    /**
     * {@inheritDoc}
     */
    public function getInformado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInformado', array());

        return parent::getInformado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcliente(\AppBundle\Entity\Clientes $idcliente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcliente', array($idcliente));

        return parent::setIdcliente($idcliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcliente', array());

        return parent::getIdcliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdestado(\AppBundle\Entity\DebitosEstados $idestado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdestado', array($idestado));

        return parent::setIdestado($idestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdestado', array());

        return parent::getIdestado();
    }

}
