<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FacturasItems extends \AppBundle\Entity\FacturasItems implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'idfacturaItem', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'idfactura', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'cantidad', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'importeUnitario', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'bonificacion', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'importeTotal', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'observacion', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'tipo', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'fechaingreso', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'identityarchivo');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'idfacturaItem', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'idfactura', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'cantidad', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'importeUnitario', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'bonificacion', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'importeTotal', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'observacion', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'tipo', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'fechaingreso', '' . "\0" . 'AppBundle\\Entity\\FacturasItems' . "\0" . 'identityarchivo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FacturasItems $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdfacturaItem()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getIdfacturaItem();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfacturaItem', array());

        return parent::getIdfacturaItem();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdfactura($idfactura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdfactura', array($idfactura));

        return parent::setIdfactura($idfactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdfactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfactura', array());

        return parent::getIdfactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidad($cantidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidad', array($cantidad));

        return parent::setCantidad($cantidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidad', array());

        return parent::getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setImporteUnitario($importeUnitario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporteUnitario', array($importeUnitario));

        return parent::setImporteUnitario($importeUnitario);
    }

    /**
     * {@inheritDoc}
     */
    public function getImporteUnitario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporteUnitario', array());

        return parent::getImporteUnitario();
    }

    /**
     * {@inheritDoc}
     */
    public function setBonificacion($bonificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBonificacion', array($bonificacion));

        return parent::setBonificacion($bonificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getBonificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBonificacion', array());

        return parent::getBonificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setImporteTotal($importeTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporteTotal', array($importeTotal));

        return parent::setImporteTotal($importeTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getImporteTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporteTotal', array());

        return parent::getImporteTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', array($observacion));

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', array());

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaingreso($fechaingreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaingreso', array($fechaingreso));

        return parent::setFechaingreso($fechaingreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaingreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaingreso', array());

        return parent::getFechaingreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentityarchivo($identityarchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentityarchivo', array($identityarchivo));

        return parent::setIdentityarchivo($identityarchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentityarchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentityarchivo', array());

        return parent::getIdentityarchivo();
    }

}
