<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EvNotas extends \AppBundle\Entity\EvNotas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'idnota', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'idcontacto', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'personacontactada', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'idcategoria', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'idoperador', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'estado');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'idnota', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'idcontacto', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'personacontactada', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'idcategoria', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'idoperador', '' . "\0" . 'AppBundle\\Entity\\EvNotas' . "\0" . 'estado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EvNotas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdnota()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdnota();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdnota', array());

        return parent::getIdnota();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcontacto($idcontacto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcontacto', array($idcontacto));

        return parent::setIdcontacto($idcontacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcontacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcontacto', array());

        return parent::getIdcontacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonacontactada($personacontactada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonacontactada', array($personacontactada));

        return parent::setPersonacontactada($personacontactada);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonacontactada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonacontactada', array());

        return parent::getPersonacontactada();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', array($observaciones));

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', array());

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcategoria($idcategoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcategoria', array($idcategoria));

        return parent::setIdcategoria($idcategoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcategoria', array());

        return parent::getIdcategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdoperador($idoperador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdoperador', array($idoperador));

        return parent::setIdoperador($idoperador);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdoperador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdoperador', array());

        return parent::getIdoperador();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

}
