<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Controlprocesos extends \AppBundle\Entity\Controlprocesos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'idcontrol', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'idcliente', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'idtipoarchivo', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'nombrearchivo', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'procesado', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'noprocesado', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'totalprocesado', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'totalregistros', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'fechaproceso', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'tipoproceso');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'idcontrol', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'idcliente', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'idtipoarchivo', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'nombrearchivo', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'procesado', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'noprocesado', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'totalprocesado', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'totalregistros', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'fechaproceso', '' . "\0" . 'AppBundle\\Entity\\Controlprocesos' . "\0" . 'tipoproceso');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Controlprocesos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdcontrol()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdcontrol();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcontrol', array());

        return parent::getIdcontrol();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcliente($idcliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcliente', array($idcliente));

        return parent::setIdcliente($idcliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcliente', array());

        return parent::getIdcliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtipoarchivo($idtipoarchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtipoarchivo', array($idtipoarchivo));

        return parent::setIdtipoarchivo($idtipoarchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtipoarchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipoarchivo', array());

        return parent::getIdtipoarchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombrearchivo($nombrearchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombrearchivo', array($nombrearchivo));

        return parent::setNombrearchivo($nombrearchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombrearchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombrearchivo', array());

        return parent::getNombrearchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcesado($procesado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcesado', array($procesado));

        return parent::setProcesado($procesado);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcesado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcesado', array());

        return parent::getProcesado();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoprocesado($noprocesado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoprocesado', array($noprocesado));

        return parent::setNoprocesado($noprocesado);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoprocesado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoprocesado', array());

        return parent::getNoprocesado();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalprocesado($totalprocesado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalprocesado', array($totalprocesado));

        return parent::setTotalprocesado($totalprocesado);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalprocesado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalprocesado', array());

        return parent::getTotalprocesado();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalregistros($totalregistros)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalregistros', array($totalregistros));

        return parent::setTotalregistros($totalregistros);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalregistros()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalregistros', array());

        return parent::getTotalregistros();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaproceso($fechaproceso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaproceso', array($fechaproceso));

        return parent::setFechaproceso($fechaproceso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaproceso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaproceso', array());

        return parent::getFechaproceso();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoproceso($tipoproceso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoproceso', array($tipoproceso));

        return parent::setTipoproceso($tipoproceso);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoproceso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoproceso', array());

        return parent::getTipoproceso();
    }

}
