<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LogueosWeb extends \AppBundle\Entity\LogueosWeb implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'idlogueo', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'idcliente', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'fechalogueo', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'clave', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'resultado', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'direccionip', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'useragent', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'codigo', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'bajonivel');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'idlogueo', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'idcliente', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'fechalogueo', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'clave', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'resultado', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'direccionip', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'useragent', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'codigo', '' . "\0" . 'AppBundle\\Entity\\LogueosWeb' . "\0" . 'bajonivel');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LogueosWeb $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdlogueo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdlogueo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdlogueo', array());

        return parent::getIdlogueo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcliente($idcliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcliente', array($idcliente));

        return parent::setIdcliente($idcliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcliente', array());

        return parent::getIdcliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechalogueo($fechalogueo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechalogueo', array($fechalogueo));

        return parent::setFechalogueo($fechalogueo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechalogueo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechalogueo', array());

        return parent::getFechalogueo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setClave($clave)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClave', array($clave));

        return parent::setClave($clave);
    }

    /**
     * {@inheritDoc}
     */
    public function getClave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClave', array());

        return parent::getClave();
    }

    /**
     * {@inheritDoc}
     */
    public function setResultado($resultado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResultado', array($resultado));

        return parent::setResultado($resultado);
    }

    /**
     * {@inheritDoc}
     */
    public function getResultado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResultado', array());

        return parent::getResultado();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccionip($direccionip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccionip', array($direccionip));

        return parent::setDireccionip($direccionip);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccionip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccionip', array());

        return parent::getDireccionip();
    }

    /**
     * {@inheritDoc}
     */
    public function setUseragent($useragent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUseragent', array($useragent));

        return parent::setUseragent($useragent);
    }

    /**
     * {@inheritDoc}
     */
    public function getUseragent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUseragent', array());

        return parent::getUseragent();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', array($codigo));

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', array());

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setBajonivel($bajonivel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBajonivel', array($bajonivel));

        return parent::setBajonivel($bajonivel);
    }

    /**
     * {@inheritDoc}
     */
    public function getBajonivel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBajonivel', array());

        return parent::getBajonivel();
    }

}
