<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MediospagoClientes extends \AppBundle\Entity\MediospagoClientes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\MediospagoClientes' . "\0" . 'idmedioCli', '' . "\0" . 'AppBundle\\Entity\\MediospagoClientes' . "\0" . 'idcliente', '' . "\0" . 'AppBundle\\Entity\\MediospagoClientes' . "\0" . 'idmedio', '' . "\0" . 'AppBundle\\Entity\\MediospagoClientes' . "\0" . 'numcliente', '' . "\0" . 'AppBundle\\Entity\\MediospagoClientes' . "\0" . 'numcliente2', '' . "\0" . 'AppBundle\\Entity\\MediospagoClientes' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\MediospagoClientes' . "\0" . 'maxcuotas');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\MediospagoClientes' . "\0" . 'idmedioCli', '' . "\0" . 'AppBundle\\Entity\\MediospagoClientes' . "\0" . 'idcliente', '' . "\0" . 'AppBundle\\Entity\\MediospagoClientes' . "\0" . 'idmedio', '' . "\0" . 'AppBundle\\Entity\\MediospagoClientes' . "\0" . 'numcliente', '' . "\0" . 'AppBundle\\Entity\\MediospagoClientes' . "\0" . 'numcliente2', '' . "\0" . 'AppBundle\\Entity\\MediospagoClientes' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\MediospagoClientes' . "\0" . 'maxcuotas');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MediospagoClientes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdmedioCli()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdmedioCli();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmedioCli', array());

        return parent::getIdmedioCli();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcliente($idcliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcliente', array($idcliente));

        return parent::setIdcliente($idcliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcliente', array());

        return parent::getIdcliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmedio($idmedio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmedio', array($idmedio));

        return parent::setIdmedio($idmedio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmedio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmedio', array());

        return parent::getIdmedio();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumcliente($numcliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumcliente', array($numcliente));

        return parent::setNumcliente($numcliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumcliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumcliente', array());

        return parent::getNumcliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumcliente2($numcliente2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumcliente2', array($numcliente2));

        return parent::setNumcliente2($numcliente2);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumcliente2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumcliente2', array());

        return parent::getNumcliente2();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxcuotas($maxcuotas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxcuotas', array($maxcuotas));

        return parent::setMaxcuotas($maxcuotas);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxcuotas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxcuotas', array());

        return parent::getMaxcuotas();
    }

}
