<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vehiculos extends \AppBundle\Entity\Vehiculos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'idvehiculo', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'idservicio', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'nrocliente', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'telefono1', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'telefono2', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'patente', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'datoadic1', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'datoadic2', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'recuperar', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'estado');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'idvehiculo', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'idservicio', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'nrocliente', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'telefono1', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'telefono2', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'patente', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'datoadic1', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'datoadic2', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'recuperar', '' . "\0" . 'AppBundle\\Entity\\Vehiculos' . "\0" . 'estado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vehiculos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdvehiculo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdvehiculo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdvehiculo', array());

        return parent::getIdvehiculo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdservicio($idservicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdservicio', array($idservicio));

        return parent::setIdservicio($idservicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdservicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdservicio', array());

        return parent::getIdservicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setNrocliente($nrocliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNrocliente', array($nrocliente));

        return parent::setNrocliente($nrocliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getNrocliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNrocliente', array());

        return parent::getNrocliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono1($telefono1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono1', array($telefono1));

        return parent::setTelefono1($telefono1);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono1', array());

        return parent::getTelefono1();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono2($telefono2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono2', array($telefono2));

        return parent::setTelefono2($telefono2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono2', array());

        return parent::getTelefono2();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', array($observaciones));

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', array());

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatente($patente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatente', array($patente));

        return parent::setPatente($patente);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatente', array());

        return parent::getPatente();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatoadic1($datoadic1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatoadic1', array($datoadic1));

        return parent::setDatoadic1($datoadic1);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatoadic1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatoadic1', array());

        return parent::getDatoadic1();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatoadic2($datoadic2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatoadic2', array($datoadic2));

        return parent::setDatoadic2($datoadic2);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatoadic2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatoadic2', array());

        return parent::getDatoadic2();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecuperar($recuperar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecuperar', array($recuperar));

        return parent::setRecuperar($recuperar);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecuperar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecuperar', array());

        return parent::getRecuperar();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

}
