<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SisTareas extends \AppBundle\Entity\SisTareas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'idtarea', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'idoperador', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'asunto', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'detalle', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'idcategoria', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'idoperadorAcargo', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'fechaingreso', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'fechasolicitfin', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'fechavisto', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'fechaestinicio', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'fechaestfin', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'fechainicio', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'fechafin', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'urgente', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'idprioridad', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'idplazo', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'internoSistemas', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'progresoEstimado', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'idestado');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'idtarea', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'idoperador', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'asunto', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'detalle', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'idcategoria', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'idoperadorAcargo', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'fechaingreso', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'fechasolicitfin', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'fechavisto', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'fechaestinicio', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'fechaestfin', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'fechainicio', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'fechafin', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'urgente', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'idprioridad', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'idplazo', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'internoSistemas', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'progresoEstimado', '' . "\0" . 'AppBundle\\Entity\\SisTareas' . "\0" . 'idestado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SisTareas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdtarea()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdtarea();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtarea', array());

        return parent::getIdtarea();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdoperador($idoperador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdoperador', array($idoperador));

        return parent::setIdoperador($idoperador);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdoperador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdoperador', array());

        return parent::getIdoperador();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsunto($asunto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsunto', array($asunto));

        return parent::setAsunto($asunto);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsunto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsunto', array());

        return parent::getAsunto();
    }

    /**
     * {@inheritDoc}
     */
    public function setDetalle($detalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetalle', array($detalle));

        return parent::setDetalle($detalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalle', array());

        return parent::getDetalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcategoria($idcategoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcategoria', array($idcategoria));

        return parent::setIdcategoria($idcategoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcategoria', array());

        return parent::getIdcategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdoperadorAcargo($idoperadorAcargo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdoperadorAcargo', array($idoperadorAcargo));

        return parent::setIdoperadorAcargo($idoperadorAcargo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdoperadorAcargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdoperadorAcargo', array());

        return parent::getIdoperadorAcargo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaingreso($fechaingreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaingreso', array($fechaingreso));

        return parent::setFechaingreso($fechaingreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaingreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaingreso', array());

        return parent::getFechaingreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechasolicitfin($fechasolicitfin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechasolicitfin', array($fechasolicitfin));

        return parent::setFechasolicitfin($fechasolicitfin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechasolicitfin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechasolicitfin', array());

        return parent::getFechasolicitfin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechavisto($fechavisto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechavisto', array($fechavisto));

        return parent::setFechavisto($fechavisto);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechavisto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechavisto', array());

        return parent::getFechavisto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaestinicio($fechaestinicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaestinicio', array($fechaestinicio));

        return parent::setFechaestinicio($fechaestinicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaestinicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaestinicio', array());

        return parent::getFechaestinicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaestfin($fechaestfin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaestfin', array($fechaestfin));

        return parent::setFechaestfin($fechaestfin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaestfin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaestfin', array());

        return parent::getFechaestfin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechainicio($fechainicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechainicio', array($fechainicio));

        return parent::setFechainicio($fechainicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechainicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechainicio', array());

        return parent::getFechainicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechafin($fechafin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechafin', array($fechafin));

        return parent::setFechafin($fechafin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechafin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechafin', array());

        return parent::getFechafin();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrgente($urgente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrgente', array($urgente));

        return parent::setUrgente($urgente);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrgente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrgente', array());

        return parent::getUrgente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdprioridad($idprioridad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdprioridad', array($idprioridad));

        return parent::setIdprioridad($idprioridad);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdprioridad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdprioridad', array());

        return parent::getIdprioridad();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdplazo($idplazo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdplazo', array($idplazo));

        return parent::setIdplazo($idplazo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdplazo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdplazo', array());

        return parent::getIdplazo();
    }

    /**
     * {@inheritDoc}
     */
    public function setInternoSistemas($internoSistemas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInternoSistemas', array($internoSistemas));

        return parent::setInternoSistemas($internoSistemas);
    }

    /**
     * {@inheritDoc}
     */
    public function getInternoSistemas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInternoSistemas', array());

        return parent::getInternoSistemas();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgresoEstimado($progresoEstimado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgresoEstimado', array($progresoEstimado));

        return parent::setProgresoEstimado($progresoEstimado);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgresoEstimado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgresoEstimado', array());

        return parent::getProgresoEstimado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdestado($idestado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdestado', array($idestado));

        return parent::setIdestado($idestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdestado', array());

        return parent::getIdestado();
    }

}
