<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CobrosSinaplicar extends \AppBundle\Entity\CobrosSinaplicar implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'idcobro', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'idservicio', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'fechaingreso', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'fechapago', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'importe', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'aplicado', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'observacionesInternas', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'idcupon');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'idcobro', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'idservicio', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'fechaingreso', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'fechapago', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'importe', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'aplicado', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'observacionesInternas', '' . "\0" . 'AppBundle\\Entity\\CobrosSinaplicar' . "\0" . 'idcupon');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CobrosSinaplicar $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdcobro()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdcobro();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcobro', array());

        return parent::getIdcobro();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdservicio($idservicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdservicio', array($idservicio));

        return parent::setIdservicio($idservicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdservicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdservicio', array());

        return parent::getIdservicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaingreso($fechaingreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaingreso', array($fechaingreso));

        return parent::setFechaingreso($fechaingreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaingreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaingreso', array());

        return parent::getFechaingreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechapago($fechapago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechapago', array($fechapago));

        return parent::setFechapago($fechapago);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechapago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechapago', array());

        return parent::getFechapago();
    }

    /**
     * {@inheritDoc}
     */
    public function setImporte($importe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporte', array($importe));

        return parent::setImporte($importe);
    }

    /**
     * {@inheritDoc}
     */
    public function getImporte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporte', array());

        return parent::getImporte();
    }

    /**
     * {@inheritDoc}
     */
    public function setAplicado($aplicado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAplicado', array($aplicado));

        return parent::setAplicado($aplicado);
    }

    /**
     * {@inheritDoc}
     */
    public function getAplicado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAplicado', array());

        return parent::getAplicado();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacionesInternas($observacionesInternas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacionesInternas', array($observacionesInternas));

        return parent::setObservacionesInternas($observacionesInternas);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacionesInternas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacionesInternas', array());

        return parent::getObservacionesInternas();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcupon($idcupon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcupon', array($idcupon));

        return parent::setIdcupon($idcupon);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcupon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcupon', array());

        return parent::getIdcupon();
    }

}
